# Generated by Django 5.2 on 2025-09-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_calories_burnt_profile_calories_consumed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='onboarding_completed',
            new_name='onboarding',
        ),
    ]
