# Generated by Django 5.2 on 2025-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_onboarding_completed_profile_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
