export const pricingStyles = {
  section: "relative py-14 bg-gray-50/95 dark:bg-gray-900",
  gradientBlur: "absolute inset-0 blur-[118px] max-w-lg h-[800px] mx-auto sm:max-w-3xl sm:h-[400px]",
  container: "relative max-w-screen-xl mx-auto text-gray-900 dark:text-gray-100 sm:px-4 md:px-8",
  header: "max-w-xl mx-auto space-y-3 px-4 sm:text-center sm:px-0",
  subheading: "text-cyan-500 font-semibold",
  heading: "text-gray-900 dark:text-white text-3xl font-semibold sm:text-4xl",
  paragraph: "text-gray-700 dark:text-gray-300",
  cardContainer: "mt-16 justify-center sm:flex gap-6",
  cardWrapper: "relative flex-1 flex flex-col mt-6 border-2 sm:mt-0 sm:rounded-xl sm:max-w-md border-transparent shadow-lg",
  cardBgGradient: "bg-gradient-to-br from-gray-100 to-gray-200 dark:from-gray-800 dark:to-gray-700",
  cardHeader: "p-6 py-8 border-b border-gray-200 dark:border-gray-700 md:p-8 flex flex-col items-center",
  cardLogo: "h-12 w-12 mb-4",
  cardName: "text-gray-900 dark:text-white font-medium text-lg",
  cardPrice: "text-gray-900 dark:text-white text-3xl font-semibold",
  cardPriceUnit: "text-xl font-normal",
  cardFeatures: "p-6 py-8 space-y-3 md:p-8",
  cardFeatureItem: "flex items-center gap-3",
  checkIcon: "h-5 w-5 text-gray-400 dark:text-gray-300",
  button: "px-4 py-3 w-full rounded-lg text-sm font-semibold text-white mt-4 transition-colors duration-200",
  buttonDisabled: "bg-gray-400 disabled:cursor-not-allowed",
  buttonHover: "hover:bg-gray-500",
  buttonActive: "active:bg-gray-600",
};